services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/app
    # ports:
    #   - "8000:8000"
    network_mode: "host"
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: celery -A config worker -l info
    env_file:
      - .env
    volumes:
      - .:/app
    network_mode: "host"
    depends_on:
      - db
      - redis

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-new_backend}
      POSTGRES_USER: ${POSTGRES_USER:-new_backend}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-new_backend}
    # ports:
    #   - "5432:5432"
    network_mode: "host"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    # ports:
    #   - "6379:6379"
    network_mode: "host"

volumes:
  postgres_data:
